## Numpy


In [7]:
import numpy as np

In [16]:
a = np.array([[[1, 2, 3], [4, 5, 6, [[7, 8, 9], [10, 11, 12]]])
a.ndim

3

In [20]:
a[1,0,2]

9

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[-5:-3]

array([3, 4])

In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:, -4:-1])

[[2 3 4]
 [7 8 9]]


In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [37]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
a[1:-2]

array([15, 20, 25, 30])

In [40]:
np.array([2.3, '2', '3'], dtype='i')

array([2, 2, 3], dtype=int32)

In [45]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[3]= 100
print(x)
print(arr)

[1 2 3 4 5]
[  1   2   3 100   5]


In [47]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape

(2, 4)

In [50]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3,1)

print(newarr)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, 2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
